### PR TITLE
Fix scrollbar jitter and not appearing when they should

### LINKED ISSUE #4: TextEditor horizontal scrollbar causes content to jitter/jump
**Bug**

**What is the current behavior?**
Text view content jumping around when scrollbar auto-appears

**Suggestion**
I'd say either have a debounce/throttle for hiding the scrollbar or once it's shown don't hide it at all. Throttling might be better.

**Environment you encounter the issue:**
gitextensions/Master @ 58f3b6c1f44260f61095df165e9c0c7b50c9f91f

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #4 and #53

Root cause for #4 only occurs when using a mouse cursor to drag the vertical scrollbar. If during drag a horizontal scrollbar is shown or hidden the text part of `TextAreaControl` gets resized by the appearance or disappearance of the scrollbar at the bottom. At the same time mouse cursor which drags the vertical scrollbar remains in the same place (adjusted for the dragging itself). This causes the vertical scrollbar to effectively get moved as the whole control "moves" under it while dragging is active.

`Notepad++` solves this by keeping the horizontal scrollbar forever if it's shown at least once.

> [!NOTE]
> This only applies to click+drag scrolling. Scroll-wheel or touch-pad scrolling is not affected 

#53 was caused by being unable to reach a "stable" state when trying to determine necessary scrollbars. e.g. 1) you need a horizontal scrollbar 2) horizontal scrollbar hides the longest line which caused it 3) hide horizontal scrollbar .. back to 1).

## Proposed changes

- Track the state of whether the mouse is still down on the scrollbar during the drag process (accomplished by `TrackableVScrollBar`)
  - Only allow horizontal scrollbar to be hidden if mouse-drag is not active
- Change scrollbar visibility calculation to need just one pass thus avoiding looking for "stable" scrollbar configuration

## Test methodology 

- Unit tests
- Used this daily for at least a month

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

### CODE REVIEW

File: Project/Src/Gui/TrackableVScrollBar.cs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    {
+        this.Scroll += VScrollBar_Scroll;
+    }
+
+    /// <summary>
+    /// Occurs when the user finishes scrolling and releases the mouse button.
+    /// </summary>
+    public event ScrollEventHandler MouseScrollEnded;
+
+    private void VScrollBar_Scroll(object sender, ScrollEventArgs e)
```
Comment (mstv) [inline Project/Src/Gui/TrackableVScrollBar.cs]:
```suggestion
    protected override void OnScroll(ScrollEventArgs se)
```

File: Project/Src/Gui/TrackableVScrollBar.cs [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+            if (IsMouseDown)
+            {
+                IsMouseDown = false;
+
+                MouseScrollEnded?.Invoke(this, e);
+            }
+        }
+    }
+
+    protected override void WndProc(ref Message m)
```
Comment (mstv) [inline Project/Src/Gui/TrackableVScrollBar.cs:37]:
```suggestion
    protected override void OnMouseDown(MouseEventArgs e)
```

File: Test/TextEditorControl/ScrollBarTests.cs [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+          bottom row
+          which
+          is
+          lower and very long and would only show HScrollBar while visible, but would get invisible once the HScrollBar is visible
+          """;
+
+        Application.DoEvents();
+
+        Assert.That(_textEditorControl.ActiveTextAreaControl.VScrollBar.Visible, Is.True);
+        Assert.That(_textEditorControl.ActiveTextAreaControl.HScrollBar.Visible, Is.True);
```
Comment (mstv) [inline Test/TextEditorControl/ScrollBarTests.cs]: We have agreed to: "Use `FluentAssertions` for assertions, i.e. do not use `ClassicAssert`." (refer to https://github.com/gitextensions/gitextensions/blob/master/.github/copilot-instructions.md)

File: Project/Src/Gui/TextAreaControl.cs [hunk 4]
```diff
@@ -46,6 +45,7 @@ public TextAreaControl(TextEditorControl motherTextEditorControl)
             Controls.Add(TextArea);
 
             VScrollBar.ValueChanged += VScrollBarValueChanged;
+            VScrollBar.MouseScrollEnded += VScrollBarOnMouseScrollEnded;
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs:48]:
```suggestion
            VScrollBar.MouseScrollEnded += (_, _) => UpdateLayout();
```

File: Project/Src/Gui/TextAreaControl.cs [hunk 5]
```diff
@@ -171,28 +176,12 @@ public void UpdateLayout()
             var view = TextArea.TextView;
 
             var currentVisibilites = GetScrollVisibilities(HScrollBar.Visible, VScrollBar.Visible);
-            var visited = new HashSet<ScrollVisibilities>();
+            var bounds = Measure(currentVisibilites);
+            var newVisibilities = ComputeScrollBarVisibilities(bounds.textArea.Size);
+            bounds = Measure(newVisibilities.visibilities);
+            ApplyLayout(newVisibilities.visibilities, newVisibilities.maxLength, bounds);
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs:182]: We use to separate the function code from nested functions by means of a `return` statement.
```suggestion
            ApplyLayout(newVisibilities.visibilities, newVisibilities.maxLength, bounds);
            
            return;
```

File: Project/Src/Gui/TextAreaControl.cs [hunk 6]
```diff
@@ -248,39 +237,67 @@ ScrollVisibilities GetScrollVisibilities(bool h, bool v)
...
-                var visibleLineCount = 1 + size.Height/view.FontHeight;
-                var visibleColumnCount = size.Width/view.WideSpaceWidth - 1;
+                var hScrollBarVisibleNow = HScrollBar.Visible;
+                var hScrollBarHeightAdjustment = hScrollBarVisibleNow
+                    ? SystemInformation.HorizontalScrollBarHeight
+                    : 0;
+
+                var partialLineHeightVisibleAtTheTop = (view.FontHeight - VScrollBar.Value % view.FontHeight) % view.FontHeight;
+
+                var visibleLineCount = (int)Math.Ceiling(((double)size.Height - partialLineHeightVisibleAtTheTop + hScrollBarHeightAdjustment)/view.FontHeight);
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs]:
```suggestion
                var visibleLineCount = (int)Math.Ceiling(((double)size.Height - partialLineHeightVisibleAtTheTop + hScrollBarHeightAdjustment) / view.FontHeight);
```

File: Project/Src/Gui/TextAreaControl.cs [hunk 7]
```diff
@@ -248,39 +237,67 @@ ScrollVisibilities GetScrollVisibilities(bool h, bool v)
...
+
+                var hScrollBarWouldCauseVScrollBar = vScrollBarVisible;
+                if (!hScrollBarWouldCauseVScrollBar && hScrollBarVisibleNow)
+                {
+                    // At this point VScrollBar is not visible, but if we show HScrollBar, it might be.
+                    // This calculation is only done if previously HScrollBar was visible and initial vScrollBarVisible
+                    // calculation was done with adjustments to account for that. Here we take the actual Height
+                    // (which is reduced due to the HScrollBar) and see if that would require a VScrollBar.
+
+                    var visibleLineCountNoAdjustment = (int)Math.Ceiling(((double)size.Height - partialLineHeightVisibleAtTheTop)/view.FontHeight);
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs]:
```suggestion
                    var visibleLineCountNoAdjustment = (int)Math.Ceiling(((double)size.Height - partialLineHeightVisibleAtTheTop) / view.FontHeight);
```

File: Project/Src/Gui/TextAreaControl.cs [hunk 8]
```diff
@@ -248,39 +237,67 @@ ScrollVisibilities GetScrollVisibilities(bool h, bool v)
...
+                    visibleLineCountNoAdjustment += partialLineHeightVisibleAtTheTop > 0 ? 1 : 0;
+                    hScrollBarWouldCauseVScrollBar = TextArea.Document.TotalNumberOfLines >= visibleLineCountNoAdjustment;
+                }
+
+                var vScrollBarWidthAdjustment = VScrollBar.Visible && !vScrollBarVisible
+                    ? SystemInformation.VerticalScrollBarWidth
+                    : 0;
+
+                var visibleColumnCount = (int)Math.Floor(((double)size.Width + vScrollBarWidthAdjustment)/view.WideSpaceWidth);
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs]:
```suggestion
                var visibleColumnCount = (int)Math.Floor(((double)size.Width + vScrollBarWidthAdjustment) / view.WideSpaceWidth);
```

File: Project/Src/Gui/TextAreaControl.cs [hunk 9]
```diff
@@ -248,39 +237,67 @@ ScrollVisibilities GetScrollVisibilities(bool h, bool v)
...
+                            lineLengthCache[lineIndex] = Math.Max(1, visualLength);
                             maxLength = Math.Max(maxLength, visualLength);
                         }
                     }
                 }
 
-                var vScrollBarVisible = VScrollBar.Value != 0 || TextArea.Document.TotalNumberOfLines >= visibleLineCount;
-                var hScrollBarVisible = HScrollBar.Value != 0 || maxLength > visibleColumnCount;
+                var hScrollBarVisible = HScrollBar.Value != 0 || maxLength > visibleColumnCount || (hScrollBarVisibleNow && VScrollBar.IsMouseDown);
+                vScrollBarVisible = vScrollBarVisible || (hScrollBarVisible && hScrollBarWouldCauseVScrollBar);
```
Comment (mstv) [inline Project/Src/Gui/TextAreaControl.cs:302]: ❔
```suggestion
                vScrollBarVisible |= hScrollBarVisible && hScrollBarWouldCauseVScrollBar;
```

**Review by mstv — COMMENTED** [review]
works well for me; nitpicks on code style (ignoring usage of `var` because commonly used for this control)

File: Project/Src/Gui/TrackableVScrollBar.cs (hunk 2 above)
Comment (mdonatas) [reply Project/Src/Gui/TrackableVScrollBar.cs:37]: Have you tried that? For me `OnMouseDown` doesn't fire which is why I had to resort to `WndProc`

File: Project/Src/Gui/TextAreaControl.cs (hunk 4 above)
Comment (mdonatas) [reply Project/Src/Gui/TextAreaControl.cs:48]: While this is simpler it doesn't follow the style of every other event registration, I'd like to leave this as is for consistency.

File: Project/Src/Gui/TextAreaControl.cs (hunk 9 above)
Comment (mdonatas) [reply Project/Src/Gui/TextAreaControl.cs:302]: The expanded variant reads easier to me, no need to spend brain-cycles expanding `|=` into what it actually means.

**Comment by mdonatas** [comment]
Thank you @mstv for the review 👍 I've made the changes except for where I still would prefer to have it the way it is.. although that's not the hill I am ready to die on :D so let me know if you have strong views on those.

File: Project/Src/Gui/TrackableVScrollBar.cs (hunk 2 above)
Comment (mstv) [reply Project/Src/Gui/TrackableVScrollBar.cs:37]: > Have you tried that? For me `OnMouseDown` doesn't fire which is why I had to resort to `WndProc`

No, I have not. A comment in the code will make it clear for further readers.

File: Project/Src/Gui/TextAreaControl.cs (hunk 9 above)
Comment (mstv) [reply Project/Src/Gui/TextAreaControl.cs:302]: To me, it raises the questions:
Is it actually the same identifier?
Why is it repeated? What does the writer intend to emphasize?
So, it is a matter of taste. That's why I added the ❔.

**Review by mstv — APPROVED** [review]

File: Project/Src/Gui/TextAreaControl.cs (hunk 9 above)
Comment (mstv) [reply Project/Src/Gui/TextAreaControl.cs:302]: There is a Roslyn analyzer which recommends "IDE0054: Use compound assignment" (refer to https://github.com/gitextensions/gitextensions/commit/a01e7122fa018a6462f7975dde627a2caa2ac808).

---

This PR is waiting for a second approval.

**Review by RussKie — APPROVED** [review]
Haven't run
