### PR TITLE
Fix Git Extensions #8211: Incorrect EOL in diff

### LINKED ISSUE #8211: Incorrect EOL in diff
## Current behaviour

When you have a change in the end-of-line character from LF to CRLF, the diff doesn't show that.

## Expected behaviour

The diff should show that the removed line had a LF while the added line has a CRLF

## Steps to reproduce
Using a windows machine with the git config core.autocrlf set to false, do the following:

1)clone the repo https://github.com/hsalameh/gitext-nonprinting-bug.git
2) open the repo in Git Extensions
3) look at the diff of commit fbd611
4) turn on the "Show nonprinting characters" option
3) as shown in the attached screenshot, the diff should show a difference at the end of the indicated line, but they appear exactly the same. The EOL character should be shown differently in the - and + lines

## Screenshots

image

## Did this work in previous version of GitExtensions

I don't know

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by lhiginbotham**
Fixes https://github.com/gitextensions/gitextensions/issues/8211: Incorrect EOL in diff

- allow the text editor to differentiate between various types of end-of-lines when displaying the EOL marker
- see [the Git Extensions integration PR](https://github.com/gitextensions/gitextensions/pull/9620) for screenshots of a before and after

### CODE REVIEW

File: Project/Src/Document/LineManager/EndOfLineType.cs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+﻿namespace ICSharpCode.TextEditor.Document
+{
+    public enum EndOfLineType
+    {
+        None,
+        CarriageReturn, // "\n"
+        CarriageReturnLineFeed, // "\r\n"
+        LineFeed // "\n"
```
Comment (RussKie) [inline Project/Src/Document/LineManager/EndOfLineType.cs]:
```suggestion
        Cr,   // "\r"
        CrLf, // "\r\n"
        Lf    // "\n"
```

File: Project/Src/Document/LineManager/EndOfLineType.cs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+﻿namespace ICSharpCode.TextEditor.Document
+{
+    public enum EndOfLineType
```
Comment (RussKie) [inline Project/Src/Document/LineManager/EndOfLineType.cs]: Maybe?
```suggestion
    public enum EndOfLineMarker
```
...or to be consistent with existing lingo:
```suggestion
    public enum EolMarker
```

File: Project/Src/Document/LineManager/LineManager.cs [hunk 3]
```diff
@@ -352,8 +363,9 @@ private void OnLineDeleted(LineEventArgs e)
 
         private sealed class DelimiterSegment
         {
+            internal EndOfLineType EndOfLine = EndOfLineType.None;
```
Comment (RussKie) [inline Project/Src/Document/LineManager/LineManager.cs]:
```suggestion
            internal EolMarker EolMarker = EolMarker.None;
```

File: Project/Src/Document/LineManager/LineSegment.cs [hunk 4]
```diff
@@ -17,6 +17,8 @@ public sealed class LineSegment : ISegment
     {
         internal LineSegmentTree.Enumerator treeEntry;
 
+        public EndOfLineType EndOfLine { get; set; }
```
Comment (RussKie) [inline Project/Src/Document/LineManager/LineSegment.cs]:
```suggestion
        public EolMarker EolMarker { get; set; }
```

**Review by RussKie — COMMENTED** [review]
👍 with few proposals to tweak the API.

File: Project/Src/Gui/TextView.cs [hunk 5]
```diff
@@ -1062,17 +1062,43 @@ private void DrawTabMarker(Graphics g, Color color, int x, int y)
...
+                    eolMarkerWidth = backslashWidth + rWidth;
+                    representation = "\\r";
+                    break;
+                case EndOfLineType.CarriageReturnLineFeed:
+                    eolMarkerWidth = backslashWidth + rWidth + backslashWidth + nWidth;
+                    representation = "\\r\\n";
+                    break;
+                case EndOfLineType.LineFeed:
+                    eolMarkerWidth = backslashWidth + nWidth;
+                    representation = "\\n";
```
Comment (gerhardol) [inline Project/Src/Gui/TextView.cs:1087]: I prefer different symbols instead, at least visually.

File: Project/Src/Document/LineManager/EndOfLineType.cs (hunk 1 above)
Comment (mstv) [reply Project/Src/Document/LineManager/EndOfLineType.cs]:
```suggestion
        Cr,   // "\r"
        CrLf, // "\r\n"
        Lf    // "\n"
```

File: Project/Src/Gui/TextView.cs [hunk 6]
```diff
@@ -1062,17 +1062,43 @@ private void DrawTabMarker(Graphics g, Color color, int x, int y)
...
+                    break;
+                default:
+                case EndOfLineType.None:
+                    // TODO: should this preserve behavior?  Not sure if this is ever called for a line without an ending,
+                    //       but if it is, then it was probably represented by '\u00B6' previously
```
Comment (mstv) [inline Project/Src/Gui/TextView.cs]: I think nothing should be drawn for `None`. The comment should be shortened.

File: Project/Src/Gui/TextView.cs (hunk 5 above)
Comment (mstv) [inline Project/Src/Gui/TextView.cs]: Just asking for opinions, @gitextensions/git-extensions-team:
My favorite diff tool uses the - more or less arbitrary but perhaps common - symbols
Cr
CrLf
Lf
Though "\r\n" is more clear for C* programmers like us - but takes more space and might raise questions from other users.

**Review by mstv — COMMENTED** [review]
👍 Just nitpicks and a poll.

File: Project/Src/Gui/TextView.cs (hunk 5 above)
Comment (gerhardol) [reply Project/Src/Gui/TextView.cs]: Personally it does not matter.
If symbols are available in supported fonts use that, otherwise suggested should be fine.

Comment (lhiginbotham) [reply Project/Src/Gui/TextView.cs]: @mstv just to be clear, are the symbols corresponding as follows?

image - Cr
image - CrLf
image - Lf

It would also be helpful to know the Unicode for each of these, but I should be able to figure it out, if these are the symbols we decide to go with.

Comment (RussKie) [reply Project/Src/Gui/TextView.cs]: I did think of that but didn't suggest because I'm not finding these glyphs obvious, whilst I do find `\r` and `\n` clear. 
I'd like to think that `\r` and `\n` are universally known to all kinds of programmers. And for those developer who may be unfamiliar with these it would be easier to do a quick online search for `\r` and `\n` than to try to lookup these glyphs... My 2c.

Comment (RussKie) [reply Project/Src/Gui/TextView.cs:1087]: Like those suggested by @mstv in https://github.com/gitextensions/ICSharpCode.TextEditor/pull/28#discussion_r724533738?

Comment (RussKie) [reply Project/Src/Gui/TextView.cs]: As an alternative, if some people don't like `\r` and `\n`, maybe render `CR`, `LF` and `CRLF` instead?

Comment (gerhardol) [reply Project/Src/Gui/TextView.cs:1087]: It seems like my initial comment was not posted the first time, I changed my mind slightly in the second comment.
The mstv symbols look nicer for newbies but I lean more to the raw \r\n symbols now.

Comment (lhiginbotham) [reply Project/Src/Gui/TextView.cs]: @RussKie Notepad++ uses CR and LF glyphs, I do not think they are part of any official font but most likely a blitted bitmap, is my guess.

image

I would rather keep it simple, if we were to choose to render CR, LF, and CRLF, I would just go for basic text rendering (which might look a little ugly compared to np++).  Personally, I would go with `\r`, `\n`, `\r\n` as it is the most clear (and like you said, programmers will usually know what these mean, and Git was designed for programmers 😄).

If you truly want, we can expose a user option so that they can choose between different styles of EOL representation (non-discriminating pilcrow [the current glyph] vs \r and \n vs @mstv's suggested glyphs or CR, LF)

File: Project/Src/Document/LineManager/EndOfLineType.cs (hunk 2 above)
Comment (lhiginbotham) [reply Project/Src/Document/LineManager/EndOfLineType.cs]: @RussKie done, thanks!

File: Project/Src/Document/LineManager/LineManager.cs (hunk 3 above)
Comment (lhiginbotham) [reply Project/Src/Document/LineManager/LineManager.cs]: Done thanks!

File: Project/Src/Document/LineManager/LineSegment.cs (hunk 4 above)
Comment (lhiginbotham) [reply Project/Src/Document/LineManager/LineSegment.cs]: Done!

File: Project/Src/Gui/TextView.cs (hunk 6 above)
Comment (lhiginbotham) [reply Project/Src/Gui/TextView.cs]: Done! Thanks!

**Comment by lhiginbotham** [comment]
@RussKie @mstv @gerhardol 

This is good to go in if we are happy with the resolution (or lack thereof) to the "what should we render?" discussion.

I think I have to update the "update submodule" PR in the main GitExtensions repo in order to capture my latest commit-squash-force-push.  I will post a (non-tagging) comment over there when that is done.

File: Project/Src/Document/LineManager/LineManager.cs [hunk 7]
```diff
@@ -352,8 +363,9 @@ private void OnLineDeleted(LineEventArgs e)
 
         private sealed class DelimiterSegment
         {
+            internal EolMarker EndOfLine = EolMarker.None;
```
Comment (RussKie) [inline Project/Src/Document/LineManager/LineManager.cs]:
```suggestion
            internal EolMarker EolMarker = EolMarker.None;
```

File: Project/Src/Document/LineManager/LineSegment.cs [hunk 8]
```diff
@@ -17,6 +17,8 @@ public sealed class LineSegment : ISegment
     {
         internal LineSegmentTree.Enumerator treeEntry;
 
+        public EolMarker EndOfLine { get; set; }
```
Comment (RussKie) [inline Project/Src/Document/LineManager/LineSegment.cs]:
```suggestion
        public EolMarker EolMarker { get; set; }
```

File: Project/Src/Gui/TextView.cs [hunk 9]
```diff
@@ -1062,17 +1062,41 @@ private void DrawTabMarker(Graphics g, Color color, int x, int y)
             DrawString(g, "\u00BB", tabMarkerColor.GetFont(TextEditorProperties.FontContainer), color, x, y);
         }
 
-        private int DrawEOLMarker(Graphics g, Color color, Brush backBrush, int x, int y)
+        private int DrawEOLMarker(EolMarker eolType, Graphics g, Color color, Brush backBrush, int x, int y)
```
Comment (RussKie) [inline Project/Src/Gui/TextView.cs]: It is customary in .NET API to pass `Graphics` as the first argument
```suggestion
        private int DrawEolMarker(Graphics g, Color color, Brush backBrush, int x, int y, EolMarker eolMarker)
```

**Review by RussKie — COMMENTED** [review]
👍 with few API suggestions

**Review by RussKie — APPROVED** [review]

**Comment by lhiginbotham** [comment]
@RussKie that was a quick response, was just about to tell you it's all good 😄

**Comment by RussKie** [comment]
:D
